### PR TITLE
[Tested] Website upgrade

### PR DESCRIPTION
**Pull request by thatrandomperson5**
Test site here: https://jdjgb-bot-beta.vercel.app/
Added some stuff, invite links about page, contact, etc.

Note:
[aec68a8](https://github.com/JDJGInc/JDJGBot-Site/pull/7/commits/aec68a86499362ae9a6107478cd4864816beac92) And the commit after are bug fixes.
ToDo after:
Add a contributors section under “about” to credit contributions on the ws

### CODE REVIEW

**Comment by thatrandomperson5** [comment]
JDJG asked me to add a invite pop-up and email som I’m doing that

**Review by CnyAnime — CHANGES_REQUESTED** [review]
Optimize the Page for Mobile user.

Edit the icons to white instead of black.

**Comment by thatrandomperson5** [comment]
> Optimize the Page for Mobile user. (Menu doesn't work)
> 
> Edit the icons to white instead of black.

Icons now white. Menu was for an older version of bootstrap and now you have to add `-bs` In the mid to make it work, added that.

**Comment by thatrandomperson5** [comment]
Added invite modal, opening pr

**Comment by JDJGInc** [comment]
@thatrandomperson5 Looks good to me, but i want other's opinions before I commit it.

**Pull request merged**
